name: pocket_patrol
description: 一个基于 Flutter 的应用，将旧手机变身为远程监控摄像头，支持通过 Tailscale 网络远程访问。仅支持 Windows 和 Android 平台。

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  video_player: ^2.7.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  camera: ^0.11.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  image: ^4.5.4
  flutter_webrtc: ^0.14.1
  qr_flutter: any
  uuid: ^4.5.1

dev_dependencies:
  # analysis_defaults:
  #   path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
